In [62]:
import csv
import pandas as pd

In [63]:
df = pd.read_csv("data.csv")
print(df.head(10))

   Unnamed: 0            timestamp    TP2    TP3     H1  DV_pressure  \
0           0  2020-02-01 00:00:00 -0.012  9.358  9.340       -0.024
1          10  2020-02-01 00:00:10 -0.014  9.348  9.332       -0.022
2          20  2020-02-01 00:00:19 -0.012  9.338  9.322       -0.022
3          30  2020-02-01 00:00:29 -0.012  9.328  9.312       -0.022
4          40  2020-02-01 00:00:39 -0.012  9.318  9.302       -0.022
5          50  2020-02-01 00:00:49 -0.012  9.306  9.290       -0.024
6          60  2020-02-01 00:00:59 -0.012  9.296  9.280       -0.024
7          70  2020-02-01 00:01:09 -0.014  9.286  9.270       -0.024
8          80  2020-02-01 00:01:19 -0.012  9.276  9.258       -0.022
9          90  2020-02-01 00:01:29 -0.012  9.264  9.248       -0.022

   Reservoirs  Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  \
0       9.358           53.600         0.0400   1.0         0.0     1.0  1.0
1       9.348           53.675         0.0400   1.0         0.0     1.0  1.0
2       9.338           53.600         0.0425   1.0         0.0     1.0  1.0
3       9.328           53.425         0.0400   1.0         0.0     1.0  1.0
4       9.318           53.475         0.0400   1.0         0.0     1.0  1.0
5       9.308           53.500         0.0400   1.0         0.0     1.0  1.0
6       9.298           53.375         0.0400   1.0         0.0     1.0  1.0
7       9.286           53.550         0.0400   1.0         0.0     1.0  1.0
8       9.276           53.425         0.0400   1.0         0.0     1.0  1.0
9       9.264           53.375         0.0400   1.0         0.0     1.0  1.0

   LPS  Pressure_switch  Oil_level  Caudal_impulses
0  0.0              1.0        1.0              1.0
1  0.0              1.0        1.0              1.0
2  0.0              1.0        1.0              1.0
3  0.0              1.0        1.0              1.0
4  0.0              1.0        1.0              1.0
5  0.0              1.0        1.0              1.0
6  0.0              1.0        1.0              1.0
7  0.0              1.0        1.0              1.0
8  0.0              1.0        1.0              1.0
9  0.0              1.0        1.0              1.0

In [64]:
df['y'] = 0
df.head()

,Unnamed: 0,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,y
0,0,2020-02-01 00:00:00,-0.012,9.358,9.340,-0.024,9.358,53.600,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0
1,10,2020-02-01 00:00:10,-0.014,9.348,9.332,-0.022,9.348,53.675,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0
2,20,2020-02-01 00:00:19,-0.012,9.338,9.322,-0.022,9.338,53.600,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0
3,30,2020-02-01 00:00:29,-0.012,9.328,9.312,-0.022,9.328,53.425,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0
4,40,2020-02-01 00:00:39,-0.012,9.318,9.302,-0.022,9.318,53.475,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0

In [66]:
df.loc[(df['timestamp'] >= '2020-04-12 11:50:00') & (df['timestamp'] <= '2020-04-12 23:30:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-04-18 00:00:00') & (df['timestamp'] <= '2020-04-18 23:59:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-04-19 00:00:00') & (df['timestamp'] <= '2020-04-19 01:30:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-04-29 03:20:00') & (df['timestamp'] <= '2020-04-29 04:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-04-29 22:00:00') & (df['timestamp'] <= '2020-04-29 22:20:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-13 14:00:00') & (df['timestamp'] <= '2020-05-13 23:59:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-18 05:00:00') & (df['timestamp'] <= '2020-05-18 05:30:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-19 10:10:00') & (df['timestamp'] <= '2020-05-19 11:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-19 22:10:00') & (df['timestamp'] <= '2020-05-19 23:59:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-20 00:00:00') & (df['timestamp'] <= '2020-05-20 20:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-23 09:50:00') & (df['timestamp'] <= '2020-05-23 10:10:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-29 23:30:00') & (df['timestamp'] <= '2020-05-29 23:59:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-05-30 00:00:00') & (df['timestamp'] <= '2020-05-30 06:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-06-01 15:00:00') & (df['timestamp'] <= '2020-06-01 15:40:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-06-03 10:00:00') & (df['timestamp'] <= '2020-06-03 11:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-06-05 10:00:00') & (df['timestamp'] <= '2020-06-05 23:59:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-06-06 00:00:00') & (df['timestamp'] <= '2020-06-06 23:29:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-06-07 00:00:00') & (df['timestamp'] <= '2020-06-07 14:30:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-07-08 17:30:00') & (df['timestamp'] <= '2020-07-08 19:00:00'), 'y'] = 2
df.loc[(df['timestamp'] >= '2020-07-15 14:30:00') & (df['timestamp'] <= '2020-07-15 19:00:00'), 'y'] = 1
df.loc[(df['timestamp'] >= '2020-07-17 04:30:00') & (df['timestamp'] <= '2020-07-17 05:30:00'), 'y'] = 2

In [80]:
df.loc[(df['y'] == 1) | (df['y'] == 2)]

,Unnamed: 0,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,y
525554,5255540,2020-04-12 11:50:01,-0.014,8.114,8.106,-0.022,8.118,54.925,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2
525555,5255550,2020-04-12 11:50:11,-0.016,8.102,8.094,-0.022,8.108,54.825,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2
525556,5255560,2020-04-12 11:50:21,-0.016,8.078,8.068,-0.024,8.082,54.825,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2
525557,5255570,2020-04-12 11:50:31,6.936,8.042,-0.028,-0.022,8.048,54.725,5.4125,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,2
525558,5255580,2020-04-12 11:50:41,8.576,8.094,-0.024,-0.022,8.096,54.600,5.8850,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183745,11837450,2020-07-17 05:29:15,5.700,5.178,-0.008,-0.014,5.172,76.250,5.0525,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,2
1183746,11837460,2020-07-17 05:29:25,5.610,5.110,-0.008,-0.014,5.106,76.200,5.0675,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,2
1183747,11837470,2020-07-17 05:29:35,5.802,5.330,-0.008,-0.014,5.326,76.175,5.0600,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,2
1183748,11837480,2020-07-17 05:29:44,5.984,5.500,-0.008,-0.014,5.496,76.100,5.0450,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2
1183749,11837490,2020-07-17 05:29:54,6.172,5.694,-0.006,-0.014,5.690,76.100,5.2050,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2

In [90]:
#print(int(0.8*len(df)))
df_offline = df.iloc[0:int(0.8*len(df)),]
df_online = df.iloc[int(0.8*len(df)):,]
print(len(df_offline), len(df_online))

1213558 303390

In [79]:

for i in range(10):
    data = df.iloc[i,].to_json()
    print(data)

{"Unnamed: 0":0,"timestamp":"2020-02-01 00:00:00","TP2":-0.012,"TP3":9.358,"H1":9.34,"DV_pressure":-0.024,"Reservoirs":9.358,"Oil_temperature":53.6,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":10,"timestamp":"2020-02-01 00:00:10","TP2":-0.014,"TP3":9.348,"H1":9.332,"DV_pressure":-0.022,"Reservoirs":9.348,"Oil_temperature":53.675,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":20,"timestamp":"2020-02-01 00:00:19","TP2":-0.012,"TP3":9.338,"H1":9.322,"DV_pressure":-0.022,"Reservoirs":9.338,"Oil_temperature":53.6,"Motor_current":0.0425,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":30,"timestamp":"2020-02-01 00:00:29","TP2":-0.012,"TP3":9.328,"H1":9.312,"DV_pressure":-0.022,"Reservoirs":9.328,"Oil_temperature":53.425,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":40,"timestamp":"2020-02-01 00:00:39","TP2":-0.012,"TP3":9.318,"H1":9.302,"DV_pressure":-0.022,"Reservoirs":9.318,"Oil_temperature":53.475,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":50,"timestamp":"2020-02-01 00:00:49","TP2":-0.012,"TP3":9.306,"H1":9.29,"DV_pressure":-0.024,"Reservoirs":9.308,"Oil_temperature":53.5,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":60,"timestamp":"2020-02-01 00:00:59","TP2":-0.012,"TP3":9.296,"H1":9.28,"DV_pressure":-0.024,"Reservoirs":9.298,"Oil_temperature":53.375,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":70,"timestamp":"2020-02-01 00:01:09","TP2":-0.014,"TP3":9.286,"H1":9.27,"DV_pressure":-0.024,"Reservoirs":9.286,"Oil_temperature":53.55,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":80,"timestamp":"2020-02-01 00:01:19","TP2":-0.012,"TP3":9.276,"H1":9.258,"DV_pressure":-0.022,"Reservoirs":9.276,"Oil_temperature":53.425,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}
{"Unnamed: 0":90,"timestamp":"2020-02-01 00:01:29","TP2":-0.012,"TP3":9.264,"H1":9.248,"DV_pressure":-0.022,"Reservoirs":9.264,"Oil_temperature":53.375,"Motor_current":0.04,"COMP":1.0,"DV_eletric":0.0,"Towers":1.0,"MPG":1.0,"LPS":0.0,"Pressure_switch":1.0,"Oil_level":1.0,"Caudal_impulses":1.0,"y":0}